# Generated by Django 4.0.5 on 2022-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('manufacture', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
                ('warna', models.CharField(blank=True, choices=[('Berwarna', 'Berwarna')], max_length=255)),
            ],
        ),
    ]
