# Generated by Django 4.0.5 on 2022-06-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_user', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('PIC', models.IntegerField()),
            ],
        ),
    ]
