# Generated by Django 4.0.5 on 2022-06-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mt', models.DateField()),
                ('cause', models.TextField()),
                ('supplier_tinta', models.CharField(max_length=255)),
                ('mt_store', models.CharField(max_length=255)),
                ('count_mt', models.IntegerField()),
                ('tgl_beli', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Operational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kertas', models.CharField(blank=True, choices=[('F4', 'F4')], max_length=10)),
                ('server', models.CharField(blank=True, choices=[('IP', 'Ip'), ('Server', 'Server')], max_length=40)),
                ('support', models.CharField(blank=True, choices=[('Non-Support', 'Non-Support'), ('Linux', 'Linux')], default='', max_length=50)),
                ('usb_lan_wifi', models.CharField(blank=True, choices=[('USB', 'Usb'), ('LAN', 'Lan'), ('WIFI', 'Wifi')], max_length=100)),
            ],
        ),
    ]
